#!/bin/bash
# =============================================================================
# Fix PJSIP local_net Configuration
# =============================================================================
#
# Fixes the local_net settings in FreePBX PJSIP transport config to include
# the correct Docker subnets.
#
# Problem:
#   FreePBX has stale local_net entries (172.23.0.0/16, 172.25.0.0/16)
#   that don't match actual Docker networks. This causes Asterisk to
#   incorrectly apply NAT to internal Docker traffic.
#
# Run this on the VPS HOST where FreePBX container is running.
#
# Usage:
#   chmod +x fix_pjsip_local_net.sh
#   sudo ./fix_pjsip_local_net.sh
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_err()   { echo -e "${RED}[ERROR]${NC} $*"; }

# ---- Configuration ----
FREEPBX_CONTAINER="${FREEPBX_CONTAINER:-}"
PJSIP_TRANSPORTS="/etc/asterisk/pjsip.transports.conf"
PJSIP_CUSTOM="/etc/asterisk/pjsip.transports_custom.conf"

# Auto-detect FreePBX container
if [ -z "$FREEPBX_CONTAINER" ]; then
    for pattern in "initpbx-freepbx-1" "initpbx_freepbx_1" "freepbx" "asterisk"; do
        if docker ps --format '{{.Names}}' | grep -q "^${pattern}$"; then FREEPBX_CONTAINER="$pattern"; break; fi
    done
    [ -z "$FREEPBX_CONTAINER" ] && FREEPBX_CONTAINER=$(docker ps --format '{{.Names}}\t{{.Image}}' | grep -i 'freepbx\|sangoma' | head -1 | awk '{print $1}')
fi

log_info "FreePBX container: ${FREEPBX_CONTAINER:-NOT FOUND}"

# Correct local_net values
# 172.30.0.0/16 = arrowz_shared_net (new shared network)
# 10.0.0.0/8    = broad private range (covers various Docker configs)
# 172.16.0.0/12 = ALL Docker bridge subnets (172.16-31.x.x) — covers current & future
# 192.168.0.0/16 = LAN
# VPS public IP
LOCAL_NETS=(
    "172.16.0.0/12"
    "10.0.0.0/8"
    "192.168.0.0/16"
    "157.173.125.136/32"
)

echo ""
echo "============================================="
echo "  Fix PJSIP local_net Configuration"
echo "============================================="
echo ""

# ---- Check container is running ----
if ! docker ps --format '{{.Names}}' | grep -q "^${FREEPBX_CONTAINER}$"; then
    log_err "Container '$FREEPBX_CONTAINER' is not running!"
    exit 1
fi

# ---- Show current config ----
log_info "Current transport config:"
docker exec "$FREEPBX_CONTAINER" cat "$PJSIP_TRANSPORTS" 2>/dev/null | grep -E "local_net|^\[" | head -20
echo ""

log_info "Current custom config:"
docker exec "$FREEPBX_CONTAINER" cat "$PJSIP_CUSTOM" 2>/dev/null
echo ""

# ---- Method 1: Fix via FreePBX custom config (preferred — survives reload) ----
log_info "Writing corrected custom transport config..."

# Build the custom config content
CUSTOM_CONFIG="; =============================================================================
; Custom PJSIP Transport Configuration for Arrowz
; =============================================================================
; Auto-generated by fix_pjsip_local_net.sh
; This file is included by pjsip.transports.conf
;
; local_net covers ALL Docker bridge subnets (172.16.0.0/12)
; so we don't need to update when Docker reassigns subnets.
; =============================================================================

; WSS Transport for WebRTC (with TLS)
[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089
cert_file=/etc/asterisk/keys/tavirapbx-fullchain.crt
priv_key_file=/etc/asterisk/keys/tavirapbx.key
method=tlsv1_2
external_media_address=pbx.tavira-group.com
external_signaling_address=pbx.tavira-group.com"

# Add local_net entries
for net in "${LOCAL_NETS[@]}"; do
    CUSTOM_CONFIG+="
local_net=$net"
done

# Write to container
echo "$CUSTOM_CONFIG" | docker exec -i "$FREEPBX_CONTAINER" tee "$PJSIP_CUSTOM" > /dev/null
log_ok "Custom config written to $PJSIP_CUSTOM"

# ---- Method 2: Also fix the main transports.conf via fwconsole ----
log_info "Updating FreePBX SIP settings via fwconsole..."

# Clear old local_net entries and set new ones via FreePBX settings
# This updates the auto-generated pjsip.transports.conf
docker exec "$FREEPBX_CONTAINER" fwconsole setting LOCALNETS '172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,157.173.125.136/32' 2>/dev/null || log_warn "fwconsole setting LOCALNETS failed — may need manual update in FreePBX GUI"

# ---- Reload Asterisk ----
log_info "Reloading PJSIP module..."
docker exec "$FREEPBX_CONTAINER" asterisk -rx "module reload res_pjsip.so" 2>/dev/null
sleep 2

# ---- Verify ----
log_info "Verified transport config after reload:"
echo ""
docker exec "$FREEPBX_CONTAINER" asterisk -rx "pjsip show transports" 2>/dev/null
echo ""

log_info "Verified local_net in config files:"
docker exec "$FREEPBX_CONTAINER" grep "local_net" "$PJSIP_TRANSPORTS" "$PJSIP_CUSTOM" 2>/dev/null
echo ""

# ---- Show registered endpoints ----
log_info "Current registered endpoints:"
docker exec "$FREEPBX_CONTAINER" asterisk -rx "pjsip show contacts" 2>/dev/null | head -20
echo ""

echo "============================================="
echo "  Done!"
echo "============================================="
echo ""
echo "local_net now covers:"
for net in "${LOCAL_NETS[@]}"; do
    echo "  ✅ $net"
done
echo ""
echo "This means Asterisk will correctly identify ALL Docker"
echo "container traffic as 'local' and won't apply external NAT."
echo ""
