services:
  freepbx:
    image: arkan-freepbx17-final-vpn4
    hostname: pbx.tavira-group.com
    privileged: true
    cgroup: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./fpbx_data/wireguard:/etc/wireguard
      - ./fpbx_data/tftpboot:/tftpboot
      - ./fpbx_data/ast_lib:/var/lib/asterisk
      - ./fpbx_data/root:/root
      - ./fpbx_data/html:/var/www/html
      - ./fpbx_data/mysql:/var/lib/mysql
      - ./fpbx_data/ast_spool:/var/spool/asterisk
      - ./fpbx_data/log:/var/log
      - ./fpbx_data/sessions:/var/lib/php/sessions
      - ./fpbx_data/etc/asterisk:/etc/asterisk
      - ./fpbx_data/etc/ssl:/etc/ssl
      - ./fpbx_data/etc/amportal.conf:/etc/amportal.conf
      - ./fpbx_data/etc/freepbx.conf:/etc/freepbx.conf
      - ./fpbx_data/etc/ssh:/etc/ssh
      - ./fpbx_data/etc/apache2:/etc/apache2
      - ./fpbx_data/etc/turnserver.conf:/etc/turnserver.conf
      - ./fpbx_data/etc/redis:/etc/redis
      - ./fpbx_data/etc/cron.d:/etc/cron.d
      - ./fpbx_data/etc/odbc.ini:/etc/odbc.ini
      - ./fpbx_data/etc/odbcinst.ini:/etc/odbcinst.ini
      - ./fpbx_data/etc/openvpn:/etc/openvpn
      - ./fpbx_data/etc/shadow:/etc/shadow
      - ./fpbx_data/etc/passwd:/etc/passwd
    ports:
      - "1322:22"
      - "127.0.0.1:8880:80"
      - "127.0.0.1:8088:8088"
      - "127.0.0.1:5038:5038"
      - "8089:8089"
      - "51600:51600/udp"
      - "51600:51600/tcp"
      - "9090:9090"
      - "10500-10700:10500-10700/udp"
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
      - "51820:51820/udp"
      - "51821:51821/udp"
      - "51822:51822/udp"
    stop_signal: SIGRTMIN+3
    restart: always
    healthcheck:
      test: ["CMD", "asterisk", "-rx", "core show uptime"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - arrowz_shared

networks:
  arrowz_shared:
    external: true
    name: arrowz_shared_net
