frappe.pages["arrowz-onboarding"].on_page_load = async function(wrapper) {
    const page = frappe.ui.make_app_page({ parent: wrapper, title: __("Arrowz Onboarding"), single_column: true });
    page.set_secondary_action(__("Skip"), () => frappe.set_route("app"));
    const $c = $(page.body).html('<div id="arrowz_onboarding-container"></div>').find("#arrowz_onboarding-container");
    const B = "#1E88E5", BL = "#BBDEFB";
    const steps = [
        { title: __("Welcome to Arrowz"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><svg viewBox="0 0 120 120" width="120" height="120"><circle cx="60" cy="60" r="55" fill="${BL}" stroke="${B}" stroke-width="3"><animate attributeName="r" values="52;55;52" dur="3s" repeatCount="indefinite"/></circle><text x="60" y="68" text-anchor="middle" font-size="36" font-weight="bold">📞</text></svg><h3 style="color:${B};margin-top:16px">${__("Arrowz")}</h3><p style="max-width:500px;margin:12px auto">${__("Enterprise VoIP, Network & WiFi Management")}</p></div>`; } },
        { title: __("WebRTC Softphone"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">📞</span><h3 style="color:${B};margin-top:12px">${__("WebRTC Softphone")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use WebRTC Softphone in Arrowz.")}</p></div>`; } },
        { title: __("Omni-Channel"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">📞</span><h3 style="color:${B};margin-top:12px">${__("Omni-Channel")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Omni-Channel in Arrowz.")}</p></div>`; } },
        { title: __("FreePBX Integration"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">📞</span><h3 style="color:${B};margin-top:12px">${__("FreePBX Integration")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use FreePBX Integration in Arrowz.")}</p></div>`; } },
        { title: __("MikroTik RouterOS"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">📞</span><h3 style="color:${B};margin-top:12px">${__("MikroTik RouterOS")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use MikroTik RouterOS in Arrowz.")}</p></div>`; } },
        { title: __("Network Monitoring"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">📞</span><h3 style="color:${B};margin-top:12px">${__("Network Monitoring")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Network Monitoring in Arrowz.")}</p></div>`; } },
        { title: __("Bandwidth Control"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">📞</span><h3 style="color:${B};margin-top:12px">${__("Bandwidth Control")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Bandwidth Control in Arrowz.")}</p></div>`; } },
        { title: __("WiFi Management"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">📞</span><h3 style="color:${B};margin-top:12px">${__("WiFi Management")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use WiFi Management in Arrowz.")}</p></div>`; } },
        { title: __("VPN Management"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">📞</span><h3 style="color:${B};margin-top:12px">${__("VPN Management")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use VPN Management in Arrowz.")}</p></div>`; } },
        { title: __("You are Ready!"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:4em">🎉</span><h3 style="color:${B};margin-top:16px">${__("Onboarding Complete!")}</h3><p style="max-width:500px;margin:12px auto">${__("You are now ready to use Arrowz. Use ❓ for help.")}</p><div style="margin-top:20px"><button class="btn btn-primary btn-lg" onclick="frappe.set_route('app')">${__("Go to Desk")}</button></div></div>`; } },
    ];
    if(frappe.visual&&frappe.visual.Storyboard) frappe.visual.Storyboard.create({container:$c[0],steps,brand_color:B,navigation:"both",showProgress:true});
    else { let h='<div style="max-width:800px;margin:0 auto;padding:20px">'; steps.forEach((s,i)=>{const d=document.createElement("div");if(s.content)s.content(d);h+=`<div style="margin-bottom:24px;padding:20px;border:1px solid var(--border-color);border-radius:12px"><h2 style="color:${B}">${s.title}</h2>${d.innerHTML||""}</div>`}); h+="</div>"; $c.html(h); }
};
